# Generated by Django 4.2.1 on 2023-05-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
