# Generated by Django 4.2.1 on 2023-05-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_admin_popularity_admin_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Latestorders',
        ),
    ]
