# Generated by Django 4.2.1 on 2023-05-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_rename_admin_latestorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Latestorders',
            new_name='Latestorder',
        ),
    ]
