# Generated by Django 4.2.1 on 2023-05-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_rename_latestorders_latestorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyAddedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
