# Generated by Django 4.2.1 on 2023-05-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_alter_recentlyaddedproducts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestorder',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recentlyaddedproducts',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='latestorder',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Shipped'), ('2', 'Pending'), ('3', 'Delivered'), ('4', 'Processing')], max_length=2, null=True),
        ),
    ]
